# Generated by Django 3.2.16 on 2022-12-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Быстрая игра', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('created_for_teams', models.BooleanField(default=False)),
                ('secret_word', models.CharField(default='', max_length=50)),
                ('all_guesses', models.TextField(default='')),
                ('similarities', models.TextField(default='')),
                ('guess_counter', models.IntegerField(default=0)),
                ('hint_counter', models.IntegerField(default=0)),
                ('is_victory', models.BooleanField(default=False)),
                ('is_revealed', models.BooleanField(default=False)),
            ],
        ),
    ]
