# Generated by Django 3.2.16 on 2022-12-24 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Команта без названия', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 12, 24, 15, 5, 2, 537326, tzinfo=utc))),
            ],
        ),
    ]
