# Generated by Django 3.2.16 on 2022-12-25 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='all_guesses',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='guess_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='hint_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='is_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_victory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='secret_word',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='similarities',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='Комната без названия', max_length=30),
        ),
    ]
