# Generated by Django 3.2.16 on 2022-12-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20221225_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_for_teams',
            field=models.BooleanField(default=False),
        ),
    ]
